### ISSUE TITLE
Does not work properly when reverse proxying is used

### ISSUE THREAD

**Issue by spapas** [cfpb/wagtail-sharing#46]
Hello, I am using reverse proxying through nginx and varnish to cache my wagtail server. The wagtail site is served from a gunicorn at port 8001 but the outisde url is served from https://example.com (i.e port 443). There's also a varnish server listening on port 81 in the middle i.e the whole chain is nginx:443 -> varnish:81 -> gunicorn:8001. 

To add the sharing site, I've added a sharing.example.com DNS entry that resolves to example.com.

Now, when I create a new sharing site for sharing.example.com:443 it does not work properly (i.e visiting the site returns the original content without the previous banner). On the other side, if I create a new sharing site for sharing.example.com:8001 it works *if I visit sharing.example.com:443* (i.e serving the draft content and displaying the banner) *but* the sharing link from wagtail admin returns http://sharing.example.com:8001/link/to/page (which does not work sincec port 8001 is bind to 127.0.0.1). 

I have instructed my editors to edit the link returned from the sharing link menu to change it properly however ideally i'd like the correct link to be returned. I understand that the whole reverse proxying situation is a little mess so maybe it would be possible to just add an optional field to the SharingSite model with the *correct* root url for that particular site ? If the option is defined then use that instead of the generated one from the `root_url` method.

TIA

**Comment by chosak** [comment]
Hi @spapas - I'd guess the relevant logic in this package is this:

https://github.com/cfpb/wagtail-sharing/blob/839b56ee19ef00b0dfa623b61dbc430c9a4c488a/wagtailsharing/models.py#L33-L36

From your description it sounds like requests to sharing.example.com:443 must be hitting Django with [`request.get_port()`](https://docs.djangoproject.com/en/4.0/ref/request-response/#django.http.HttpRequest.get_port) returning 8001.

Is Nginx setting the `X-Forwarded-Port` HTTP header so that downstream servers see the original request port? If so, and if [`settings.USE_X_FORWARDED_PORT`](https://docs.djangoproject.com/en/4.0/ref/settings/#use-x-forwarded-port) is enabled, then I believe `request.get_port()` should return 443 as expected, and sharing should work as desired.

(Note: this might have some other side effects - I would expect that, from the way you describe your current setup, you might already see various :8001 URLs, if that's where Django thinks it is running. Unless Varnish already strips these out?)

**Comment by spapas** [comment]
Hello @chosak thank you for the tip! After adding the `proxy_set_header X-Forwarded-Port 443;` on my nginx conf and `USE_X_FORWARDED_PORT =` True on my django project settings the sharing site works great!

Kind regards,
Serafeim
