### ISSUE TITLE
Wagtail 5.0 Upgrade

### ISSUE THREAD

**Issue by nickmoreton** [cfpb/wagtail-sharing#65]
This isn't an issue but question raised on one of the other packages you maintain: https://github.com/cfpb/wagtail-inventory/pull/73

At TBX we are letting older versions of packages support versions up to one LTS behind the one we are upgrading to. 

Would you prefer to keep support for earlier versions before I start the work? Thanks

**Comment by chosak** [comment]
Wagtail 5.0 is now officially supported in release [2.11](https://github.com/cfpb/wagtail-sharing/releases/tag/2.11). As mentioned [here](https://github.com/cfpb/wagtail-sharing/pull/69#issuecomment-1819742184), the next release of wagtail-sharing will only support 5.1 and above due to complications around supporting both modeladmin and snippets.
